openapi: '3.0.3'
info:
  title: Sistema de Gerenciamento Financeiro
  version: '1.0'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'

paths:
  /users:
    get:
      operationId: get
      summary: Acessar usuários
      responses:
        '200':
          description: OK
      
    post:
      summary: Cadastrar um usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome do usuário
                  example: Kaiane
                email:
                  type: string
                  description: Email do usuário
                  example: kaiane.xxxx@gmail.com
                job:
                  type: string
                  description: Função do usuário
                  example: Mestre de obras
                password:
                  type: string
                  description: Senha do usuário
                  example: '123123'

      responses:
        201:
          description: Usuário criado
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: O URI do novo recurso criado.
        400:
          description: Requisição inválida

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Acessa um usuário
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  job:
                    type: string
                  password:
                    type: string
        404:
          description: Não encontrado

    delete:
      summary: Apaga um usuário
      responses:
        200:
          description: Ok
        404:
          description: Não encontrado.

    put:
      summary: Altera um usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: O nome da pessoa.
                  example: Kaiane
                idade:
                  type: integer
                  description: A idade da pessoa.
                  example: 19
      responses:
        200:
          description: OK
        404:
          description: Não encontado.



                
